UPDATE MONITORING.CONTROLS.REPLICATION_ENTITY_REST_API_V1
SET
    RUNNING_STATUS = 1,
    LAST_RUN_ID = %(last_run_id)s,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE SOURCE_INSTANCE = %(source_instance)s
  AND STATUS_ID = 1
AND RUNNING_STATUS = 0;

SELECT *
FROM MONITORING.CONTROLS.REPLICATION_ENTITY_REST_API_V1
WHERE SOURCE_INSTANCE = %(source_instance)s
  AND STATUS_ID = 1
  AND RUNNING_STATUS = 1
  AND LAST_RUN_ID = %(last_run_id)s;
